### ISSUE TITLE
Add some unit tests

### ISSUE THREAD

**Issue by dguest** [dguest/lwtnn#21]
Good news everyone!

I added Travis CI integration into master (see the `.travis.yml` file). If anyone is interested (@Marie89, @mickypaganini), it would be fun to try adding some unit tests. Basically what I have in mind:

 - Call the tests `lwtnn-unittest-XXX`, they can live in `scripts/` or `bin/`
 - They have to return non-zero on failure for Travis CI to realize something is wrong, see [the example output](https://travis-ci.org/dguest/lwtnn/builds/128830365#L292) that I'm turning on with the likes [here](https://github.com/dguest/lwtnn/blob/0c0d53e5f20951b92f1f283edab0a8d3b6a92a31/.travis.yml#L25)
 - I'd rather not include much (or any) data in the repository (since git won't handle raw hdf5 well) but just checking to make sure the output of some of the basic nets doesn't change with new commits would already be very useful.

Obviously this is just for "fun", so low priority but it may also be very useful down the road.

**Comment by mickypaganini** [comment]
Nice, I was looking into that too actually! I can expand on it a bit if needed. As you said, this might be low priority now, but before I push anything I run all these checks by hand anyways, so we may as well automate them. Thanks for adding this.

**Comment by dguest** [comment]
Cool, actually the tests I've created aren't super useful so more extensive ones would be welcome. As I said before I don't really want to include HDF5 files in the repository, but I can think of a few other tests:
 - I wrote [a script that generates fake Keras outputs][1], which won't work right now (because it was for pre 1.0), but could be used for simple cases.
 - We could generate some _very simple_ intermediate JSON files and put them in the `data/` directory. This would also be useful if we ever end up changing the format, since we might end up with earlier versions of the JSON format uploaded to Athena which we still need to support.
 - We can also just run `wget` and download trained nets to the Travis CI nodes from (for example) CERN public pages. We should try to keep the file size minimal obviously, but I just checked with a 40 MB file and Travis didn't give me any problems.

[1]:https://github.com/dguest/lwtnn/blob/master/scripts/lwtnn-build-dummy-inputs.py

**Comment by dguest** [comment]
Great, I just closed #22, which in which @mickypaganini added highway layers. I implemented a test which downloads the network from my CERN webspace, which seems like a fine solution to deal with much bigger files. Anyone can also run the test locally by executing `./tests/test-highway.sh`.

Once we have some production-ready RNNs and feed-forward networks, it would be great to add some tests for them too.

**Comment by dguest** [comment]
I think this is "complete"—I added a few unit tests that cover the basic cases, so we now have build tests, and automatic tests for the keras and agilepack (anyone actually using it?) converters. Specific tests should be their own issue. To start with, we should probably add at least one test that starts with each JSON file that we actually end up using, to ensure that we don't update the JSON format (i.e. in #4) and break something.
