### ISSUE TITLE
RNN preprocessing

### ISSUE THREAD

**Issue by makagan** [dguest/lwtnn#24]
If I understand, preprocessing is done by default for RNN's.  I think we need to make this optional.  For instance, we don't so any preprocessing for our RNN's.  Also, there is some ambiguity if the pre-processing (if done) should be per time step, or over all time steps.  Can we add the functionality to turn this off if desired?

**Comment by dguest** [comment]
The preprocessing is just applying a normalization and an offset to each variable. So if you use an offset of 0 and a normalization of 1 it will do nothing. Will that do what you need?

**Comment by makagan** [comment]
Gotcha, yeah, that should work
