### ISSUE TITLE
Keras converter

### ISSUE THREAD

**Issue by Marie89** [dguest/lwtnn#3]
Probably good to add the Keras-to-JSON converter in the next weeks to have the full process chain up and running.

**Comment by dguest** [comment]
Indeed, see #1, which is basically asking for the same thing

**Comment by dguest** [comment]
This should be pretty much done now, although I still have to run some some tests to make sure it's doing what I think it's doing.

**Comment by dguest** [comment]
Converter is in place, passes basic sanity checks.
