### ISSUE TITLE
Implement Maxout

### ISSUE THREAD

**Issue by dguest** [dguest/lwtnn#5]
It would be useful to support maxout. This should be pretty trivial, but there's some room for bugs storing the weights so it will have to be tested carefully.

**Comment by dguest** [comment]
I've implemented (what I think Keras is using as) maxout in the `maxout` branch, [around line 80][1], and added the necessary code to the JSON parser.

I'm not sure if Keras uses a bias vector for the maxout layers, so at the moment they aren't supported in the C++ code. I also haven't added support to the Keras -> JSON converter.

@Marie89, can you send me an example Keras NN for me to try this out on?

[1]: https://github.com/dguest/lwtnn/blob/maxout/src/LightweightNeuralNetwork.cxx#L80

**Comment by Marie89** [comment]
Sure. I put the files you need on [CERNbox](https://cernbox.cern.ch/index.php/s/NnO6xbwR84lbcTJ).
The architecture of this NN is [simpleMaxout](https://gitlab.cern.ch/malanfer/Keras-stuff/blob/master/scripts/btagging_nn.py#L239) with `tanh` activation function.

Let me know if you need additional information or prefer a different structure and I will adapt the outputs.

**Comment by dguest** [comment]
@Marie89, the converter in the `maxout` branch should now support the NN you sent. I haven't had time to do more than basic sanity checks, so it's probably worth running `lwtnn-test-arbitrary-net` on an example and confirming that it does the same thing as Keras.

**Comment by dguest** [comment]
I'm going to call this complete, since we've been able to confirm that maxout layers are doing what we'd expect. It may be worth doing more extensive tests since maxout is piecewise, meaning a test on a single pattern _could_ hide a problem, but it's hard to imagine how the implementation we have could do that.

**Comment by Marie89** [comment]
Consider this validated in Athena using a combination of multiple MO+FC layers:
{
  "keras_prediction": {
    "b-jet": 0.025388296693563461,
    "c-jet": 0.078963674604892731,
    "u-jet": 0.044128954410552979
  }
}
ToolSvc.DL1Tag                                      DEBUG #BTAG# NN output b: 0.0253884 c: 0.0789638 u: 0.044129
